loglevel: debug
neo4j:
  host: localhost
  port: 7687
  user: neo4j
  password: password

objectStorage:
  minio:
    host: "localhost:9000"
    user: calculator
    password: c@1cu1@t0r
    secure: false
    bucket: calculator