loglevel: debug
neo4j:
  host: localhost
  port: 7687
  user: neo4j
  password: password

minio:
  host: minio-console.local.net:1234
  user: minio
  password: password
  secure: false
  bucket: calculator